### ISSUE TITLE
Time date issue - timezone

### ISSUE THREAD

**Issue by jOOc** [custom-cards/upcoming-media-card#1]
Couldn't reply on the forum (New users have a limit on 21 messages per day) so created an issue here.

And to reply to your message, no the dates/times does not change if I remove my change in the code.
I still need my change to get it to show names of the weekdays.
I think your times are correct but they are not for my timezone, that's why it was confusing.
Looked at Sonarr API and for me `airDateUtc` seams like a better date/time value.

![image](https://user-images.githubusercontent.com/9382342/44940749-02964380-ad93-11e8-8403-9d7aab0c6371.png)

![image](https://user-images.githubusercontent.com/9382342/44940775-44bf8500-ad93-11e8-8c24-ea2333cd246c.png)

**Comment by maykar** [comment]
Since our previous conversation, I have updated the card to use UTC exclusively. Give it a shot and see if it helps. Sorry, I just saw this issue. Had notifications off for some reason.

**Comment by maykar** [comment]
Going to close this one, seems like removing locale reliance and switching over to UTC did the trick. Thanks again, jOOc .
