### ISSUE TITLE
[Feature Request] Sonos

### ISSUE THREAD

**Issue by gieljnssns** [custom-cards/upcoming-media-card#13]
Can you make this Sonos-compatible?

**Comment by maykar** [comment]
I cannot as I do not use sonos myself, but if anyone is up to the task the card is open for other developers to create components for it.

**Comment by iantrich** [comment]
I just happened to be here and stumbled across this...what does Sonos provide for upcoming media? I think there is some confusion here @gieljnssns

**Comment by gbdavidx** [comment]
@iantrich i think your confused, what do you want sonos to be able to provide? this is for media you have on a hard drive....

**Comment by iantrich** [comment]
Yes, I am, hence why I asked for clarification. I guess I see how that wording could have been in itself confusing, but to be clearer; what does it mean to be Sonos-compatible? What does Sonos contain that would be considered upcoming media to consume?

**Comment by gbdavidx** [comment]
Sonos is just a speaker playing media from a source

**Comment by gbdavidx** [comment]
if you want a feature request, maybe they could add upcoming media for music?

**Comment by iantrich** [comment]
I mean, I think we're on the same page here, @gbdavidx. There's no real context to this feature request, i.e. no way to implement it and should probably just be closed.

**Comment by gieljnssns** [comment]
I was searching a way to see 'or manage' my Sonos queue....

**Comment by maykar** [comment]
Though I believe this would be useful to view the upcoming items in the Sonos queue, I don't believe the Sonos API currently supports it (with the limited research I've done). I'll look into it more but this would require Sonos API support and a developer that uses Sonos to implement.

**Comment by gieljnssns** [comment]
@maykar 
http://docs.python-soco.com/en/latest/examples.html?highlight=queue#seeing-and-manipulating-the-queue

**Comment by maykar** [comment]
Cool, so its possible. I think this should stay open in hopes that someone will create a component for it.

**Comment by iantrich** [comment]
Perhaps a separate feature request for handling music is in order?

**Comment by titomontes** [comment]
Now that it is mentioned, it would be nice to have a Sonos playlist viewable in Lovelace. I´m not sure if UMC is capable of handling that though...

**Comment by JackJPowell** [comment]
Hi everyone,

I ran across this request the other day and thought it would make for a fun side project. It's my first time working on a home assistant component, or writing in python for that matter, so I'm open to suggestions or improvements. 

Here is the repo for the [sonos_upcoming_media](https://github.com/JackJPowell/sensor.sonos_upcoming_media) sensor. It outputs a user configurable number of upcoming tracks from your sonos queue for [upcoming-media-card](https://github.com/custom-cards/upcoming-media-card) to parse and display. 

![image](https://user-images.githubusercontent.com/7500683/125113692-f8563100-e0b6-11eb-83f0-881437757157.png)

**Comment by gbdavidx** [comment]
Would be cool to be able to change the media player type for something like
blue sound audio

**Comment by JackJPowell** [comment]
> Would be cool to be able to change the media player type for something like blue sound audio

I didn't find anything authoritative, but it looks like the control mechanism for the speakers is fairly simple and some libraries have been built around it. Looks like there even may be an [endpoint ](https://github.com/ClausRN/BluesoundAPI/blob/master/README.md)to return the play queue. Sadly, without a bluesound speaker to test with I can't really go any further. This feature request should probably be moved to its own issue too.

**Comment by mkanet** [comment]
Hi guys, Im going to close this issue since there hasn't been activity on it for years.
