### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by labachev** [custom-cards/upcoming-media-card#18]
Images are downloaded but not loading into the UI. 
When I check the URL it is showing system path where the images are saved.

My config is:

  - platform: plex_recently_added
    token: MY_TOKEN
    host: MY SERVER PUBLIC IP
    port: PUBLIC PORT
    download_images: true
    max: 5

What might be the problem?

**Comment by maykar** [comment]
Sounds like this is an issue for [the plex component](https://github.com/custom-components/sensor.plex_recently_added), but what system are you running home assistant on? Where are the images being stored? If you manually visit one of the url's for the images showing in the sensor under dev tools does it display? Have you set any custom path with "img_dir" in your config?

**Comment by labachev** [comment]
Hi,
I am on Windows. 
The images are stored in the default location "www\custom-lovelace\upcoming-media-card\images\plex".

The path in dev tools is a bit wrong:

"C:\\Users\\homesrv\\AppData\\Roaming\\.homeassistant/../local/custom-lovelace/upcoming-media-card/images/plex/f377.jpg"

No custom path is set.

**Comment by labachev** [comment]
It seems it does not take the correct HA URL.

**Comment by maykar** [comment]
Use the img_dir option in plex components config to point to the correct directory

**Comment by labachev** [comment]
The directory is correct.
Home assistant URL is not.

This is the issue.

I am not sure from where is taken.

**Comment by maykar** [comment]
Going to have to look into it after Christmas, not running HA on windows myself so I can't really give you a quick fix nor do I  have any way to replicate it. Will look into it though.

**Comment by maykar** [comment]
Closing this and adding the issue to the plex component's issues. If you wish to be updated, subscribe to the issue there.

**Comment by maykar** [comment]
Also not sure if it fits you're setup, but checkout the "download_images: false" option on the plex components readme. It could fix your issue as long as you can meet the requirements.

**Comment by maykar** [comment]
Please try the latest version.

**Comment by labachev** [comment]
Now it is working! 

Thank you very much and Happy New Year! :)
