### ISSUE TITLE
sickrage ?

### ISSUE THREAD

**Issue by swetoast** [custom-cards/upcoming-media-card#2]
there is a sickrage component for ha too :) dunno how you pull the data for sonarr and radarr  but just tell me what format you need it in and ill make that happen for the sickrage component its also hosted on custom_components

**Comment by maykar** [comment]
if you look towards the bottom of the readme there are instructions on how to create your own component for this card

**Comment by maykar** [comment]
Going to close this one, feel free to message me over on the forums. @mayker over there, maykar on here to save some confusion.

**Comment by swetoast** [comment]
awesome will add once i get back to it busy with work but sooner or later i get a little time over for development again
