### ISSUE TITLE
Fanart and Poster are not shown in Lovelace UI

### ISSUE THREAD

**Issue by murmelbahn** [custom-cards/upcoming-media-card#23]
**Describe the Bug**
I dont see any images of the upcoming medias. No poster and no fanart but they are included in my kodi library.

**Home Assistant Version**
0.87.0

**Screenshots**
https://imgur.com/a/3o5ifTW

**Additional Context**
Here are the data of the sensor:

data: [{"title_default": "$title", "line1_default": "$genres", "line2_default": "$release", "line3_default": "$rating - $runtime", "line4_default": "$studio", "icon": "mdi:arrow-down-bold"}, {"aired": "2018-10-24", "airdate": "2019-02-03T12:44:52Z", "flag": true, "genres": "Drama,Musik", "rating": "\u2605 8.2", "release": "$date", "runtime": 135, "title": "Bohemian Rhapsody", "studio": "GK Films,Regency Enterprises,Queen Films,Tribeca Productions,New Regency Pictures,20th Century Fox", "fanart": "media/3TB1/Filme/Bohemian Rhapsody (2018)/fanart.jpg", "poster": "media/3TB1/Filme/Bohemian Rhapsody (2018)/poster.jpg"}, {"aired": "2018-09-28", "airdate": "2018-12-06T22:20:07Z", "flag": true, "genres": "Science Fiction,Action", "rating": "\u2605 6.6", "release": "$date", "runtime": 112, "title": "Venom", "studio": "Avi Arad Productions,Matt Tolmach Productions,Pascal Pictures,Marvel Entertainment,Tencent Pictures", "fanart": "media/3TB1/Filme/Venom (2018)/fanart.jpg", "poster": "media/3TB1/Filme/Venom (2018)/poster.jpg"}, {"aired": "1988-04-16", "airdate": "2018-11-21T15:01:05Z", "flag": true, "genres": "Fantasy,Zeichentrick,Familie", "rating": "\u2605 8.1", "release": "$date", "runtime": 86, "title": "Mein Nachbar Totoro", "studio": "Studio Ghibli,Nibariki,Tokuma Japan Communications Co. Ltd.", "fanart": "media/3TB1/Filme/Mein Nachbar Totoro (1988)/fanart.jpg", "poster": "media/3TB1/Filme/Mein Nachbar Totoro (1988)/poster.jpg"}, {"aired": "2018-07-13", "airdate": "2018-11-20T16:06:50Z", "flag": true, "genres": "Action,Thriller,Abenteuer", "rating": "\u2605 7.3", "release": "$date", "runtime": 148, "title": "Mission: Impossible - Fallout", "studio": "Paramount,Bad Robot,Skydance Media,TC Productions,Alibaba Pictures Group"

**Comment by maykar** [comment]
This is an issue for the kodi component and not this card
