### ISSUE TITLE
[Feature Request] Day Translations

### ISSUE THREAD

**Issue by JeffreyBouman** [custom-cards/upcoming-media-card#24]
**Is your feature request related to a problem? Please describe.**
Even though my user settings are set to another language, the days are not translated to the set language, I am sure they are available.

**Describe the solution you'd like**
What I would like to see, if possible, is for the card to tap into the translation database already maintained within Home Assistant to translate the names of the day. If possible the movie categories would be nice addition, although I do not know for sure whether those translations are available or not.

**Comment by maykar** [comment]
This card uses "toLocaleString" to translate using system settings:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

Surprisingly, it doesn't seem that days of the week are included in hass translations:
https://github.com/home-assistant/home-assistant-polymer/tree/master/translations

I will look into making this a config option as you can use toLocaleString with a specified locale

**Comment by mkanet** [comment]
@JeffreyBouman, I'm going to close this ticket since it's been years since there's been any activity on it.  Lots has changed in Home Assistant as well in UMC. Please open a new issue if you still don't have a solution or workaround.
