### ISSUE TITLE
Custom element doesn't exist: upcoming-media-card

### ISSUE THREAD

**Issue by topexnative** [custom-cards/upcoming-media-card#25]
Hi all,

Sorry if this has been posted to death - but i'm at a loss now!
Things i've done:

1. sensor.yaml config

# Plex recently added
- platform: plex_recently_added
  token: TOKEN CORRECT - URL RETURNS DATA
  server_name: SERVER_NAME
  ssl: false
  ssl_cert: false
  download_images: true
  max: 5
  section_types:
    - movie
    - show
  
# Sonarr upcoming media
- platform: sonarr_upcoming_media
  api_key: API CORRECT - CHECKED WITH URL TO HOST
  host: 192.168.1.x
  port: 8989
  days: 2
  ssl: false
  max: 10
  
# Radarr upcoming media
- platform: radarr_upcoming_media
  api_key: TOKEN CORRECT - DOUBLE CHECKED
  host: 192.168.1.x
  port: 7878
  days: 120
  ssl: false
  theaters: false
  max: 10

2.  JS File location (Using RAW editor on LL UI) - note: have copied the RAW code from Github rather than downloading the ZIP

![image](https://user-images.githubusercontent.com/7575174/53012165-1bacc100-34a7-11e9-89c1-4d2b0a35676b.png)

3. Followed both the custom card and custom component instructions (well, at least i think i have)

4. Here is what the card looks like

![image](https://user-images.githubusercontent.com/7575174/53012350-9bd32680-34a7-11e9-91f9-62fccb81e96e.png)

5. HA Log file output

![image](https://user-images.githubusercontent.com/7575174/53012411-cd4bf200-34a7-11e9-9fa6-10c25ba85475.png)

Please someone help me before i go crazy!!!  I'm sure it's something basic i've overlooked :(

**Comment by topexnative** [comment]
As you can probably guess, i'm not a coder.  But i am a tech.

**Comment by maykar** [comment]
each service should be it's own card so try something like this:  
```
- type: 'custom:upcoming-media-card'
  entity: sensor.sonarr_upcoming_media
- type: 'custom:upcoming-media-card'
  entity: sensor.radarr_upcoming_media
- type: 'custom:upcoming-media-card'
  entity: sensor.plex_recently_added
```

**Comment by topexnative** [comment]
Sorry yes will do next time.  I've tried what you suggested but now i just get the same message as 4. but with 3 separate cards

![image](https://user-images.githubusercontent.com/7575174/53039102-369d2680-34e3-11e9-9335-76068d3e4b1f.png)

**Comment by iantrich** [comment]
@topexnative did you download the `.js` file and put it in your `www` directory and then define it in your `resources` section?

**Comment by topexnative** [comment]
> @topexnative did you download the `.js` file and put it in your `www` directory and then define it in your `resources` section?
> 
> Edit: Missed that you said you have both those.
> 
> Any errors in the browser console?

Yep i put the .js file in www/custom-lovelace/upcoming-media-card/upcoming-media-card.js

and just get this error in chrome (although this is happening in FF and Edge:

![image](https://user-images.githubusercontent.com/7575174/53041108-fc825380-34e7-11e9-95ba-90522ca735d5.png)

**Comment by topexnative** [comment]
Question, does it need to be under /custom-lovelace/upcoming-media-card/ folder structure?  Or can it be under www/ direct?

**Comment by maykar** [comment]
If you put it anywhere other than www/custom-lovelace/upcomming-media-card/ then you need to update your resources portion to reflect that

**Comment by topexnative** [comment]
> If you put it anywhere other than www/custom-lovelace/upcoming-media-card/ then you need to update your resources portion to reflect that

Oh wow - just jumped back on then you messaged :)

Yes gotcha.  So tried installing another custom component (mini-media-player) and getting the exact same error after following the instructions to the letter.  - thoughts?

**Comment by maykar** [comment]
Please share your entire lovelace code, be sure to format it as a code block and not just copy paste. Formatting is crucial for these things and it's very difficult to see your formatting if it's not a code block.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by topexnative** [comment]
Sure (remembering i'm not a coder) - what's the easiest way of presenting this to you then?  > Blockcode?

**Comment by maykar** [comment]
copy and paste, but be sure to use the info from the link in my previous post to correctly format it

**Comment by maykar** [comment]
if you're not using yaml mode in HA then you will have to select configure-UI > raw config editor to show all of your code. I would also suggest reading up on lovelace:
https://www.home-assistant.io/lovelace/how-it-works/

**Comment by maykar** [comment]
You may also be having trouble with the custom components. I'm going to close this issue for now as I don't think this is an actual issue with this card. Please read through the readme of this card and follow the troubleshooting guide.  If you're still having issues, resubmit an issue using the bug template.

**Comment by DavidFW1960** [comment]
![image](https://user-images.githubusercontent.com/36390762/53061569-22bce900-3512-11e9-9629-6db3dbad29f7.png)

You have MIS-SPELLED RESOURCES....... that will screw things up but good!!

**Comment by topexnative** [comment]
> ![image](https://user-images.githubusercontent.com/36390762/53061569-22bce900-3512-11e9-9629-6db3dbad29f7.png)
> 
> You have MIS-SPELLED RESOURCES....... that will screw things up but good!!

Doh! - will correct that shortly and see what happens.  @maykar i've shared my yaml file with you

**Comment by maykar** [comment]
Yaml looks fine except for the spelling error. Hopefully that should do it for you. Sorry, I didn't spot that sooner.

**Comment by topexnative** [comment]
> Yaml looks fine except for the spelling error. Hopefully that should do it for you. Sorry, I didn't spot that sooner.

No problem - trees through the forest :)  I'm getting somewhere however, as now i'm not getting the custom element doesn't exist, meaning that it is probably the components that are either incorrectly setup or misconfigured - thanks @DavidFW1960  and @maykar for your help here.
