### ISSUE TITLE
A compact Fanart View - with possible solution at bottom

### ISSUE THREAD

**Issue by 4meuwil** [custom-cards/upcoming-media-card#26]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Essentially more content in space....fanart style but with 2 items per line OR a fanart minimum with half the height and less info displayed, or choose which info is displayed

**Additional context**

**Comment by maykar** [comment]
You can already customize each lines text. So, you're just looking for something that takes even less space than fanart view? I played with the idea of using other types of art (show icons, banners, etc.) but far too often they were unavailable even with popular shows/movies. Fanart and posters are almost always available. I've also thought about maybe a text only version. Mind expanding on what you'd like to see here?

**Comment by maykar** [comment]
The two options I see for making fanart take up half the height are:

1. Shrink it: This would leave far too much empty space on one side and fanart would be very small.
2. Crop it: Since fanart is designed differently per show/art there would be a good bit of shows with art that ended up being cropped  incorrectly. Some might just crop to the background, while some might have a close up of crotches.

**Comment by 4meuwil** [comment]
Is the height of each entry "box" determined by the fanart size? I found where i could change the width to 75% but it just shrunk it all within the card.....just wish i had more items in the same amount of card space. everything is so large i have the results set to 5...which isn't much of a heads up what is actually available. I just don't want to scroll a ton. Also, if it was set to a panel on a 20" screen, could we define a numbers of columns to really fill up the screen. I just don't know how to make custom cards myself...wish i did so I could edit as needed. Card is amazing as is though....good work.

**Comment by maykar** [comment]
The ratio is hard coded and everything shrinks to the width of the column. I don't really see a solution that would look good other than text only at the moment, but I will think on it and see if there might be another "slimmer" solution. I do like the idea of an entire screen of shows for panel view, will have to play with that as well.

**Comment by 4meuwil** [comment]
![morecontent](https://user-images.githubusercontent.com/44265003/53996545-6c0a5c80-40fe-11e9-8eb1-74089f91891f.png)

**Comment by 4meuwil** [comment]
without the date added and blank space at bottom, twice as many entries in same space...i just don't know how you do that

**Comment by maykar** [comment]
If you want to play with the styling to get something similar:
@ line 142 of upcoming-media-card.js add `height:100px;` under the width like so:

```
      style.textContent = `
        .${service}_${view} {
          width:100%;
          height:100px;
```

That'll get you started.

**Comment by 4meuwil** [comment]
added height: 80px as above, changed margin-bottom right below that to 5px, and removed {line[2]}$ from fanart render section....seems much better for my tastes....thank you for the help

**Comment by 4meuwil** [comment]
and <polygon points="100 30,95 0,100 0"></polygon> in fanart render section to fix flag shape

**Comment by 4meuwil** [comment]
and `<polygon points="100 30,95 0,100 0"></polygon>` in fanart render section

**Comment by maykar** [comment]
mind posting a screenshot of it?

**Comment by maykar** [comment]
Also, if you just use the config options for line contents you wont need to edit the  <text> section

**Comment by 4meuwil** [comment]
![70px](https://user-images.githubusercontent.com/44265003/54034098-a82fd280-417b-11e9-80eb-c08a5bb07528.png)

**Comment by 4meuwil** [comment]
ended up with 10 entries in nearly the same space 5 was using....

**Comment by 4meuwil** [comment]
I tired using style options but couldn't get them to affect anything....i tried direct in config and also under a style: header....not sure.

**Comment by iantrich** [comment]
dr pimple popper? wtf?
