### ISSUE TITLE
 Cannot read property 'icon' of undefined

### ISSUE THREAD

**Issue by ezraholm50** [custom-cards/upcoming-media-card#27]
Hey,

Without any further issues, the logs output this:

`https://192.168.x.x:8123/local/customcards/upcoming-media-card.js?track=true:24:45 Uncaught TypeError: Cannot read property 'icon' of undefined`

All latest versions as of today card/hassio

Clean all warnings/errors, please advise. 
Thanks for all the effort!

**Comment by maykar** [comment]
"Failure to follow the issue template will result in your issue being closed."

Please, resubmit your issue and follow the template given.
