### ISSUE TITLE
Annoying Flicker

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/upcoming-media-card#30]
## Describe the bug:

The card flickers a couple of times randomly from normal view to the screenshot attached.
## Config YAML:

```
entity: sensor.upcoming_episodes
image_style: poster
type: 'custom:upcoming-media-card'
```

## Components:

Using Trakt Sensor
## HA Error:

No Error
## Troubleshooting Guide:

Yes
## Home Assistant Version:

0.92.1
## Screenshots:

![Screen Shot 2019-05-12 at 09 53 32](https://user-images.githubusercontent.com/34303331/57579427-e3ac8d00-749b-11e9-91ba-4d8f29437244.png)
![Screen Shot 2019-05-12 at 09 54 18](https://user-images.githubusercontent.com/34303331/57579451-40a84300-749c-11e9-91cf-2b890fb24c4e.png)

**Comment by maykar** [comment]
Please, try the latest release and see if that fixes the issue. If not could you look at your trakt sensor and post one of the image URLs here?

**Comment by iantrich** [comment]
I've never seen this myself with the trakt component, FYI, so curious to hear more.

**Comment by PierreScerri** [comment]
Downloaded latest upcoming-media-card and Trakt sensor files and it seems to have fixed the issue.
