### ISSUE TITLE
Run Away Style Loading

### ISSUE THREAD

**Issue by derekleeds** [custom-cards/upcoming-media-card#31]
## Describe the bug:

Style for Fanart keeps loading repeatedly. 

## Config YAML:

`entity: sensor.plex_recently_added
image_style: fanart
title: Recently Downloaded
type: 'custom:upcoming-media-card'`

`entity: sensor.radarr_upcoming_media
image_style: fanart
title: Upcoming Movies
type: 'custom:upcoming-media-card'`

`entity: sensor.sonarr_upcoming_media
image_style: fanart
title: Upcoming TV
type: 'custom:upcoming-media-card'`

## Components:

upcoming-media-card
sonarr_upcoming_media
radarr_upcoming_media
plex_recently_added

## Home Assistant Version:

HA ver 0.93.0
## Screenshots:

[Screen Capture of Chrome Inspector](https://cloud.remoteaccess.network/index.php/s/zsfwbEPj3d3j8pr)

**Comment by maykar** [comment]
Thanks for finding this, just released 0.3.5 to remedy the situation.

**Comment by derekleeds** [comment]
I updated to the 0.3.5, but the same issue is present for me. [Screenshot](https://lwslink.us/2QbgRzs)

**Comment by maykar** [comment]
Looks like it's a caching issue and it's still using the old version of the card. If you installed manually be sure to increase the version number at the end of the resource url and either do a hard refresh (Ctrl +Shift+R) or clear your cache.

**Comment by maykar** [comment]
Let me know if you're still having issues

**Comment by derekleeds** [comment]
There is an error being displayed in the code below, which is loaded for each item in the table. 

`<div class="rada_fanart style='undefined'" style="background-position:100% 0;background-image:url('https://image.tmdb.org/t/p/w780/7u2p0VxnhVMHzfSnxiwz5iD3EP7.jpg')">`

The first `style='undefined'" doesn't seem to be proper html.

**Comment by maykar** [comment]
Yup, there's a typo in there. Misplaced quotation marks.

Is everything else working as expected now?

**Comment by derekleeds** [comment]
@maykar with exception to the continual reloading of the elements, yes. I can provide screen capture of chrome inspector if needed.

**Comment by maykar** [comment]
If the style tag that is repeating doesn't look like this `<style id="umc_style">` then you're still using an older version of the card. Either it's not updating or the old version is cached on your system.

**Comment by derekleeds** [comment]
I've reinstalled the card and flushed my cache. Here is what I am seeing [screen capture of chrome inspector](https://cloud.remoteaccess.network/index.php/s/kt4ALRD3cbG252t). The Custom Updater/Tracker Card shows that I have 0.3.6 installed of the upcoming-media-card.

**Comment by maykar** [comment]
Looks like its working as intended. The flashing you are seeing is the card being updated with a normal lovelace update.

**Comment by maykar** [comment]
When an entity updates Lovelace "refreshes" elements. This is from my testing install that probably has far less entity updates than your install so I'm just toggling an input boolean to illustrate.

![UMC_update_flash](https://user-images.githubusercontent.com/25127328/57963976-0fe06780-78fb-11e9-99a5-a8fcf7ebf698.gif)

**Comment by maykar** [comment]
I can definitely limit it though by checking for changes in the json instead and will work on that.

**Comment by maykar** [comment]
This is quite literally my first project in JS. I've not really touched it in months and have come a long way since then. If you can think of anything else, let me know. Now that development is slowing down on compact-custom-header I can work on this again.

**Comment by iantrich** [comment]
Time for that Lit rewrite 🤣 then you can just use shouldUpdate function

**Comment by maykar** [comment]
That and move everything out of `set hass` heh.

**Comment by maykar** [comment]
@derekleeds Until I actually get around to rewriting the card, I added a check for sensor update and it will now only update the card if the corresponding sensor has changed. In the latest release 0.3.8
