### ISSUE TITLE
Install cards on HA Docker

### ISSUE THREAD

**Issue by karkaaa** [custom-cards/upcoming-media-card#37]
Hello,

I install HA on docker and i can not run your cards. 

I not found any www, local or config dir's.

Only this loaded in the log:

> INFO (SyncWorker_4) [homeassistant.loader] Loaded sonarr_upcoming_media from custom_components.sonarr_upcoming_media

**Comment by maykar** [comment]
Please refer to thomasloven's guide for how to install custom lovelace plugins:

https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins
