### ISSUE TITLE
[Feature Request] Add Lidarr Support

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [custom-cards/upcoming-media-card#43]
**Is your feature request related to a problem? Please describe.**
The upcoming media card currently only supports Sonarr (TV Shows) and Radarr (Movies) based on the NzbDrone codebase. There is however, a reletive newcomer project to the NzbDrone offshoots called Lidarr which handles Music.

**Describe the solution you'd like**
Add Lidarr functionality in similar form to Sonarr and Radarr

**Comment by JackJPowell** [comment]
Hey @danieledwardgeorgehitchcock

Here is the sensor you requested, setup just like the Sonarr sensor with lidarr as its data source. I have some updates in mind but figured you'd like to check things out as is and provide some feedback. It's based heavily off of @maykar work on the sonarr sensor. :)

![image](https://user-images.githubusercontent.com/7500683/125167641-986f9100-e16f-11eb-9d36-c995b5b32cf8.png)

**Comment by bckthomas** [comment]
Hi @JackJPowell 
How can I integrato to HA and use this sensor for lidarr ?
Thanks

**Comment by JackJPowell** [comment]
> Hi @JackJPowell I'm very interested ! How can I integrate this to HA and use this sensor for lidarr ? Thanks

Hey @bckthomas,

Do you already have the [upcoming-media-card](https://github.com/custom-cards/upcoming-media-card) installed? If not, follow the direction in the readme to include the resources in your home assistance instance. 

Next, like the directions in the above state, you need to supply it with sensors. The easiest option to install the lidarr sensor is using HACS. If you don't have that in your home assistant environment yet, google how to install it. Once done, add my [git repo](https://github.com/JackJPowell/sensor.lidarr_upcoming_media) to you list of custom repositories in HACS using the upper right menu. Then proceed to install using HACS. It's straight forward. Do a restart as HACS suggests.

You'll then need to edit your configuration.yaml file to supply the sensor with your lidarr specific info. The readme in my repo has all the info. Once that is done, do one more restart and add an upcoming media card to your lovelace ui. Something like this:

```
type: custom:upcoming-media-card
entity: sensor.lidarr_upcoming_media
title: Upcoming Music
hide_empty: false
image_style: fanart
```

et voilà !

**Comment by mkanet** [comment]
Closing this issue since there appears to be a lidarr integration already.
