### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ikrowni** [custom-cards/upcoming-media-card#45]
Could you add the option to have x columns in the card? currently i have to scroll down through about 20 banners which i dont feel looks nearly as good if i could just have 3 columns to complete and entire page dedicated to my media

**Comment by maykar** [comment]
This won't be something I would add, but it can be achieved by using [Horizontal Stacks](https://www.home-assistant.io/lovelace/horizontal-stack/)

**Comment by maykar** [comment]
I spoke too soon as horizontal stacks would only duplicate the card, but not start at the next needed episode. Either way this is a duplicate of #38
