### ISSUE TITLE
Card not working: Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by maxi1134** [custom-cards/upcoming-media-card#47]
## Describe the bug:

I installed the Plugin and Addon (through Hassio and HACS). And upon creating the card,
I receive the Cannot read property 'setConfig' of undefined error message.

## Config YAML:
`  - platform: plex_recently_added
    token: TOKEN
    host: 192.168.0.20
    port: 32400`

## Components:

sensor.plex_recently_added

## HA Error:
None

## Troubleshooting Guide:
I did follow the guide.

## Home Assistant Version:
Home Assistant 0.108.0

## Screenshots:
![image](https://user-images.githubusercontent.com/1342643/79289467-4e79fb80-7e97-11ea-9957-f43336b2c987.png)

**Comment by Kekehuaite** [comment]
Did you integrate it on ui-lovelace.yaml ? 

```
ressources:
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.4.0
  type: module
```

**Comment by maykar** [comment]
Did you add the resource either in your HA settings or, if you use YAML mode, in ui-lovelace.yaml.

**Comment by maxi1134** [comment]
I apologize for the delay,

HACS was to blame, reinstalling HACS and the card worked.

I apologize again, i've been quite busy lately.

**Comment by marothe** [comment]
I am getting the same error. I installed the upcoming media card frontend integration via HACS and I can see it:

![image](https://user-images.githubusercontent.com/29024610/83915728-19da4000-a774-11ea-8d25-e8619f9f975c.png)

Though, I am getting the same erorr:

![image](https://user-images.githubusercontent.com/29024610/83915795-3d9d8600-a774-11ea-9015-1697a48cd3a7.png)

Restarted HA as well. Any ideas?

**Comment by maykar** [comment]
If you're not using the raw config editor then it should look like the following image with the hyphen and indentation removed.

![image](https://user-images.githubusercontent.com/25127328/83916758-b801e200-a743-11ea-9a6b-c473f222f5ce.png)


If you're still having issues:

* Double check that the file exists in /community/upcoming-media-card/upcoming-media-card.js
* Clear cache

**Comment by marothe** [comment]
Oh man, so easy - I am just so lost with lovelace. Thank you so much for your quick help. 
It worked with the hyphen and the correct indentation.

**Comment by marothe** [comment]
Actually, I do have another question: 
It is added now, but it does not display anything? Although I can see posters in the folders, which I assume means, the connection to Plex is working?

![image](https://user-images.githubusercontent.com/29024610/83921112-ffa55f80-a77d-11ea-966d-19f3df2893da.png)

![image](https://user-images.githubusercontent.com/29024610/83921132-07fd9a80-a77e-11ea-8d6d-0a80c0de23ad.png)

Sorry for all these noob questions. Still getting the hang of HA tbh.

**Comment by maykar** [comment]
Looks like you named your sensor "recently_added_movies" and not "plex_recently_added_movies".

Meaning your entity in the card's config would be `entity: sensor.recently_added_movies`

**Comment by marothe** [comment]
Oh man. I think it's just too late and I am too tired. Embarrassing. Thank you very much!
