### ISSUE TITLE
No images on casting

### ISSUE THREAD

**Issue by isabellaalstrom** [custom-cards/upcoming-media-card#48]
## Describe the bug:
When I use the ability to cast a Lovelace view to a chromecast, the images for upcoming media doesn't show up. I belive it to be the same reason as this, and the solution would be to include the whole path to the image, not relative path. https://github.com/custom-cards/button-card/issues/271

**Comment by maykar** [comment]
Yup, you're spot on, just haven't got around to this one yet. Been putting off this project for a while. It was my very first project and is very, very poorly written. Desperately needs a rewrite, but I should be able get this in there soon.

**Comment by maykar** [comment]
Added in the latest version
