### ISSUE TITLE
Custom card is completely empty on Home screen

### ISSUE THREAD

**Issue by mkanet** [custom-cards/upcoming-media-card#49]
## Describe the bug:
Custom card is completely empty.  No information or graphics displayed.

## Config YAML:
```
 type: 'custom:upcoming-media-card'
 entity: sensor.sonarr_upcoming_media
```
## Components:
**Sonarr Upcoming Media**

## HA Error:
No errors

## Troubleshooting Guide:
None of these issues seem applicable to me

## Home Assistant Version:
HASSIO - latest

## Screenshots:
![broken](https://user-images.githubusercontent.com/811008/80760093-3805ae00-8aed-11ea-9ea8-40f74ee4fafe.png)

## Additional Context:
I installed both **Upcoming Media Card** and **Sonarr Upcoming Media** via HACS and rebooted.
I added the below lines to my `ui-lovelace.yaml` file _(per HACS Upcoming Media Card addon instructions)_:

```
resources:
  - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
    type: module
```
The below lines are in the **Raw Configuration Editor** under the cards section:

```
      - type: 'custom:upcoming-media-card'
        entity: sensor.sonarr_upcoming_media
```

I added the below lines to my `configuration.yaml` file _(per instructions for Sonarr):_

```
sensor:
- platform: sonarr_upcoming_media
  api_key: 285e90a22afe48f3b05925ef15fdc2a1
  host: 192.168.1.2
  port: 9989
  days: 2
  ssl: false
  max: 10
```

I can get to the below URL using any web browser on my LAN:
**http://192.168.1.2:9989**

I have uninstalled and reinstalled the respective addons from HACS and rebooted.  It didn't make any difference.  I am certain the API key is correct.  Hopefully, I'm missing something simple.  However, I tried my best to follow all applicable troubleshooting instructions with no luck.

EDIT:  I'm not sure if this is relevant, but below is the path to the respective js file _(which was added by HACS when I installed the addon)_:
`./config/www/community/upcoming-media-card/upcoming-media-card.js`

**Comment by maykar** [comment]
There are two very important questions that can be answered by following the troubleshooting guide: Does the sensor report any data? Can you connect directly to the API using the URL's in the guide?

Also, check that you're not using an overactive ad blocker in your browser by whitelisting your HA page.

**Comment by mkanet** [comment]
Thanks for the quick reply back.  Below is a screenshot of the sensor data:
![1](https://user-images.githubusercontent.com/811008/80766371-237be280-8afa-11ea-8697-103dec0aafab.png)

Also, querying API works just fine; returning correct data:
`http://192.168.1.2:9989/api/calendar?apikey=285e90a22afe48f3b05925ef15fdc2a1&start=2018-10-31&end=2019-05-15`

Response:
```
[
  {
    "seriesId": 284,
    "episodeFileId": 6417,
    "seasonNumber": 1,
    "episodeNumber": 4,
    "title": "Doom Patrol",
    "airDate": "2018-11-02",
    "airDateUtc": "2018-11-02T13:00:00Z",
    "overview": "Gar brings Rachel home to his “family” – a group of misfit medical experiments we’ll come to know as The Doom Patrol (including Robotman, Negative Man and Elastigirl).",
    "episodeFile": {
      "seriesId": 284,
      "seasonNumber": 1,
      "relativePath": "Season 1\\Titans - S01E04 - Doom Patrol Bluray-1080p.mkv",
      "path": "E:\\TV\\Titans\\Season 1\\Titans - S01E04 - Doom Patrol Bluray-1080p.mkv",
      "size": 3299885945,
      "dateAdded": "2020-02-02T04:46:20.1587Z",
      "sceneName": "Titans.S01E04.2018.BluRay.1080p.DTS-HD.MA.5.1.x264-CHD",
      "quality": {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p",
          "source": "bluray",
          "resolution": 1080
        },
        "revision": {
          "version": 1,
          "real": 0
        }
      },
      "mediaInfo": {
        "audioChannels": 5.1,
        "audioCodec": "DTS",
        "videoCodec": "x264"
      },
....
```

**Comment by maykar** [comment]
Since you have the sensor set to only show the next 2 days of shows, could it be that you have no shows that are being released in that time frame?

**Comment by mkanet** [comment]
My current calendar schedule:
![Screenshot](https://user-images.githubusercontent.com/811008/80767001-a5b8d680-8afb-11ea-8c25-0cf46eba0419.png)

**Comment by maykar** [comment]
Does the [default HA sonarr sensor](https://www.home-assistant.io/integrations/sonarr/) work for you?

**Comment by mkanet** [comment]
I'm not sure how to check.  Could you please let me know what to do to test?

**Comment by maykar** [comment]
These are all questions that are contained in the troubleshooting guide and the link in my last comment shows how to setup the default sensor.

Although, I just added the show Upload to my Sonarr and it immediately caused the sensor to return blank. So, it's most likely just something odd with that show and I'll look into it.

**Comment by mkanet** [comment]
Please forgive me, I don't really understand how to add a default HA sonarr sensor when looking at the link you sent me.  I'm still very new to HA.  I'm not sure if this is related, but if I press the + icon on the home screen and add a pre-built card related to this addon, I see the card below when I move my mouse over the purple area:
![cantbereached](https://user-images.githubusercontent.com/811008/80768669-df8bdc00-8aff-11ea-8726-3e984c9df47d.png)

The sensor for the card above is:
**sensor.sonarr_upcoming_media**

**Comment by mkanet** [comment]
PS:  I changed the number of days from 2 to 7 and rebooted HA.  The card is still empty.

**Comment by maykar** [comment]
Like I mentioned above, this seems to be an issue with the show "Upload", I'm not sure what's causing it yet, but after tomorrow I'm sure the sensor will start working again.

**Comment by mkanet** [comment]
Ok.  Thank you very much for your patience.  I'll try it again tomorrow and post back here.

**Comment by mkanet** [comment]
I am seeing stuff from sonarr now.  However, I'm getting inconsistent results with the posters between my mobile phone or using my PC's web browser.  Is what I'm seeing currently, related to this issue?  Will this not happen with another TV show?

**Mobile phone:**  Home Assistant App
![Screenshot_20200501-171853_Home Assistant](https://user-images.githubusercontent.com/811008/80850384-6a3c0c00-8bd0-11ea-9ff9-543a698fa5a3.jpg)

**PC Web Browser:** Chrome
![Screenshot](https://user-images.githubusercontent.com/811008/80850404-863fad80-8bd0-11ea-96e6-d87f09ef2a5f.png)

**Comment by mkanet** [comment]
I am still having this bizarre issue where the posters for either Plex TV or Sonarr TV are missing; depending on which device I view the Home Assistant interface on.  Could you please check to see if I have the sensors setup correctly in my configuration.yaml?  If my sensors are setup correctly; including the format.  Would you know how I can resolve this issue?

```
sensor:
  - platform: sonarr_upcoming_media
    api_key: 285e90a22afe48f3b05925ef15fdc2a1
    host: 192.168.1.2
    port: 9989
    days: 2
    ssl: false
    max: 10

  - platform: plex_recently_added
    name: Recently Added TV
    token: Yon7AhysmB-riPyzvWbX
    host: 192.168.1.2
    port: 32400
    section_types:
    - show

  - platform: plex_recently_added
    name: Recently Added Movies
    token: Yon7AhysmB-riPyzvWbX
    host: 192.168.1.2
    port: 32400
    section_types:
    - movie

```

**Comment by maykar** [comment]
For the missing images in Chrome: Whitelist the HA page in your ad blocker.

For the ones on your phone: It is a known issue that will be fixed in the next release of Plex Recently added. [See issue here](https://github.com/custom-components/sensor.plex_recently_added/issues/34)

**Comment by maykar** [comment]
Also, you should try to always censor your api keys and tokens when posting anywhere. Even if you haven't posted a public address, just a good rule to follow. ;)

**Comment by mkanet** [comment]
Thank you for all your help.  Looking forward to the fix for multiple sensors.  I will also not post my tokens.
