### ISSUE TITLE
guide needs an update

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-cards/upcoming-media-card#5]
the guide says:
make sure its on its own folder yes?
Be sure to include it in its own folder like so: www/custom-lovelace/sonarr-upcoming-card/sonarr-upcoming-card.js 

the script preview says:
resources:
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  type: js

thats not going to work
cheers mate

**Comment by maykar** [comment]
Thanks!
