### ISSUE TITLE
Error after upgrade Home Assistant 0.110.1

### ISSUE THREAD

**Issue by markbooth73** [custom-cards/upcoming-media-card#51]
## Describe the bug:

After upgrade to HA 0110.1 the card no longer works and i get the error as indicated in the log below
## HA Error:

https://redacted.duckdns.org/hacsfiles/upcoming-media-card/upcoming-media-card.js:323:18 Uncaught TypeError: Cannot read property 'includes' of undefined
10:32:02 – components/system_log/__init__.py (ERROR) - message first occurred at 7:34:27 and shows up 4 times
## Home Assistant Version:

latest

**Comment by maykar** [comment]
Please, try the latest release ( 0.4.2 ) and report back.

**Comment by Maltavius** [comment]
Same issue with 0.4.2

I haven't changed anything in my Lovelace since the upgrade, only upgraded HACS and upcoming-media-card and plex-recently-added (which contains data)

![image](https://user-images.githubusercontent.com/10133945/82947970-3242a180-9fa1-11ea-9753-00934be1febf.png)

**Comment by maykar** [comment]
@Maltavius are you seeing the same error as @markbooth73 ? Have you cleared your cache after upgrading.

**Comment by markbooth73** [comment]
Sorry for not getting back sooner but I can confirm card is working fine, my instance is with emby.

Sent from Yahoo Mail on Android 
 
  On Tue, 26 May 2020 at 21:47, Ryan Meek<notifications@github.com> wrote:   


@Maltavius are you seeing the same error as @markbooth73 ? Have you cleared your cache after upgrading?

**Comment by Maltavius** [comment]
I can't be sure since I can't find that error message. I've tried in a private browser session and I have the same error there.

**Comment by maykar** [comment]
Press F12 and see if there are any related errors in your browser's dev console, try reinstalling from hacs and clearing cache.

**Comment by maykar** [comment]
If you're still having issues, please open an new one as this one has been resolved.
