### ISSUE TITLE
[Feature Request] Show only Poster with no text to side

### ISSUE THREAD

**Issue by atomicpapa** [custom-cards/upcoming-media-card#55]
Would it be possible to have the card ONLY show the poster (or potentially fanart)?  Currently I can set all text entities to empty but that only results in
![image](https://user-images.githubusercontent.com/6396499/94489358-eb142980-01a9-11eb-90b3-92fc268d1763.png)
 Whereas, I would like for it to only show
![image](https://user-images.githubusercontent.com/6396499/94489470-20207c00-01aa-11eb-95fb-4eae1ab57e16.png)

**Comment by maykar** [comment]
This isn't something that I would add, but you can create something like this on your own pretty easily. All the components I made for this card return JSON that can be used elsewhere, using that data you can really make anything you want with a bit of jinja.

Here's a HA markdown card using the just the images from the first 4 episodes from plex_recently_added (change "poster" to "fanart" if you'd rather have that):

```
      - type: markdown
        content: >
          ![]({{ state_attr('sensor.plex_recently_added','data')[1]["poster"]}})
          
          ![]({{state_attr('sensor.plex_recently_added', 'data')[2]["poster"]}})

          ![]({{ state_attr('sensor.plex_recently_added','data')[3]["poster"]}})

          ![]({{ state_attr('sensor.plex_recently_added','data')[4]["poster"]}})
```

**Comment by maykar** [comment]
Someone on the forums just asked a similar question and I thought I would share an updated markdown card that I used for them. This one uses a for loop to iterate over every item:

```yaml
type: markdown
content: |-
  {% for item in state_attr('sensor.plex_recently_added', 'data') %}
    {% if item.poster %} ![]({{ item.poster }}) {% endif %}
  {% endfor %}
```
