### ISSUE TITLE
[Feature Request] Change the unwatched (hide_unflagged: true) logic

### ISSUE THREAD

**Issue by 4841penoyer** [custom-cards/upcoming-media-card#57]
With Kodi looks like the flag is watched or unwatched. 

When I set hide_unflagged to false the 5 most recent movies are displayed, when I set it to true nothing is displayed.  I played so more with it and set the max to 15 then 2 movies showed up.  

It looks like when it queries it grabs the first 5 (max) records and then selects the ones without flags. 

I would like the behavior to be grab records until it finds the 5 (max) most recent un-flagged

**Comment by maykar** [comment]
This would be a request for the Kodi Component, not this card.

**Comment by maykar** [comment]
The feature request would be to add an option for the Kodi component to only return unwatched. This card can only filter what the component feeds it. So if the component is only supplying 2 unwatched items, that's all it can filter.

The other option is increasing the max, as you've found out.
