### ISSUE TITLE
Upcoming Media Card not showing up on HA 0.117

### ISSUE THREAD

**Issue by gcorgnet** [custom-cards/upcoming-media-card#59]
## Describe the bug:
The card is not displaying on Lovelace after upgrade to HA 0.117. There is an error in the Chrome Console

## Config YAML:
```
  - type: custom:upcoming-media-card
    entity: sensor.sonarr_upcoming_media
```
## Components:
Sonarr andf Radarr. The card doesn't work with any component.

## HA Error:
```
upcoming-media-card.js:16 Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.set hass [as hass] (upcoming-media-card.js:16)
    at HTMLElement._createCardElement (swipe-card.js:21)
    at async Promise.all (index 0)
    at async HTMLElement._createCards (swipe-card.js:21)
```

## Home Assistant Version:
0.117

## Screenshots:
![image](https://user-images.githubusercontent.com/4731735/97763145-9c262f00-1b6f-11eb-82ed-a492513c6430.png)

**Comment by maykar** [comment]
Working fine here, looks like it may be in combination with swipe card? Have you tried it outside of swipe card?

**Comment by maykar** [comment]
Actually, it's working fine in swipe card for me as well.

**Comment by maykar** [comment]
Make sure upcoming media card and any component you are using with it is at the latest version. Looking back on some issues posted on the forums I found this same error https://community.home-assistant.io/t/lovelace-upcoming-media-card/66562/191

They needed to update the components used for the card.

**Comment by gcorgnet** [comment]
Sorry, my bad, got it working after messing around with it.
