### ISSUE TITLE
no banner view

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-cards/upcoming-media-card#6]
Hi men, im getting the unfortuntely there is no banner view for this content. The sensos raddarr works as the states getting valig jpg files. What can i do to get it work.

Also i have setup radarr the same way as radarr, but from this sensor im not getting any data or states.
Here is my setup: https://github.com/IIIdefconIII/homeassistant

**Comment by IIIdefconIII** [comment]
changed the media type to tv

**Comment by maykar** [comment]
You have `media_type: movies` for sonarr, which is tv and also you shouldn't be using that config option anyway. Its for devs to test components they make for the card.

**Comment by maykar** [comment]
Normally I appreciate issues brought to my attention, but please post issues like these to the home assistant forum post. These are not issues with the card or components, these are issues with your setup. The kind folks over there would be glad to help out.
