### ISSUE TITLE
Chrome/Firefox browser (no images) safari and mobile has images

### ISSUE THREAD

**Issue by fireheadman** [custom-cards/upcoming-media-card#60]
Have flushed cache in chrome/firefox, just not getting images to populate.  Have also tried in private browser mode.
<img width="792" alt="image" src="https://user-images.githubusercontent.com/19847195/97795662-3b7a0f00-1bce-11eb-8cba-d8ac5f15a91d.png">

Mobile devices and safari browser will properly display images.
Unsure if this is a javascript compat issue?

<img width="449" alt="image" src="https://user-images.githubusercontent.com/19847195/97795672-5b113780-1bce-11eb-9ae5-13cea6023879.png">

I can test any procedures and/or try any recommendation.
Thanks

**Comment by fireheadman** [comment]
corrected..... found your HA thread about adblocker.
Seems a lot of people run into this issue... maybe a short blurb about having people add an exception and/or disable it?

**Comment by maykar** [comment]
Well, it is the first item in the [troubleshooting guide](https://github.com/custom-cards/upcoming-media-card/blob/master/troubleshooting.md).
