### ISSUE TITLE
Fan Art images not showing

### ISSUE THREAD

**Issue by crider17** [custom-cards/upcoming-media-card#63]
## Describe the bug:
The Fan Art for my Sonarr upcoming-media card is not showing. 

## Config YAML:
`  - platform: sonarr_upcoming_media
     api_key: MY API
     host: HOST IP
     port: PORT
     days: 7
     ssl: false
     max: 10`

Raw Configuration Editor:
`      - type: 'custom:upcoming-media-card'
        entity: sensor.sonarr_upcoming_media
        title: Upcoming TV
        image_style: fanart`

## Components:
sensor.sonarr_upcoming_media

## Troubleshooting Guide:
Yes.

## Home Assistant Version:
2020.12.7

## Screenshots:
![image](https://user-images.githubusercontent.com/28905331/104678933-85956b80-56ba-11eb-8fa6-d12e835ed0e4.png)

## Additional Context:
I'm not sure if this is an issue with the card or the component, but I think the card. 

Sensor Data:
`- airdate: '2021-01-16T01:00:00Z'
  release: '$day, $time'
  flag: false
  title: Shark Tank
  episode: 'Slice of Sauce, Love is Project, Luna Magic, Bubbly Blaster'
  number: S12E10
  runtime: 45
  studio: ABC (US)
  rating: ★ 8.1
  genres: Reality
  poster: 'https://artworks.thetvdb.com/banners/posters/100981-1_t.jpg'
  fanart: 'https://artworks.thetvdb.com/banners/fanart/original/100981-1_t.jpg'`

**Comment by maykar** [comment]
I assume you followed the first item in the troubleshooting guide and whitelisted HA in your adblocker?

**Comment by crider17** [comment]
Thanks for the quick reply! I did initially by adding the page via Chrome while on it. It works now but I had to remove the /path text and just whitelist the IP address of the pi. Looks good now. Thanks again!
