### ISSUE TITLE
Add "data:image/png;base64,..." support for Fanart and Poster

### ISSUE THREAD

**Issue by andrewjswan** [custom-cards/upcoming-media-card#64]
## Describe the bug:

No bug, extension

## Config YAML:

---

## Components:

Custom MQTT component for Mediaportal

## HA Error:

No error

## Additional Context:

If i change this line: https://github.com/custom-cards/upcoming-media-card/blob/master/upcoming-media-card.js#L322
To:
`if (image && !image.includes("http") && !image.includes("data:image")) {`
All work fine, out of the box, upcoming-media-card add http://ha:port/data:image .... and image not work ...

**Comment by mkanet** [comment]
Sorry it took so long to respond.  A lot has changed in UMC since you opened this issue.  Please try the latest UMC.  If you still dont have a solution/workaround, please open a new issue with updated details.
