### ISSUE TITLE
Only displays one upcomming show

### ISSUE THREAD

**Issue by FallenLeave91** [custom-cards/upcoming-media-card#7]
Hi there,

like the Title says. The card only displays one show. 
This is the output of the sensor
```
banner1: https://www.thetvdb.com/banners/graphical/75978-g6.jpg
poster1: https://www.thetvdb.com/banners/_cache/posters/75978-13.jpg
fanart1: https://www.thetvdb.com/banners/_cache/fanart/original/75978-13.jpg
extrainfo1: ★ 8.6 - FOX (US)
title1: Family Guy
subtitle1: Pal Stewie
airdate1: 2018-10-15T01:00:00Z
hasFile1: false
info1: S17E03
banner2: https://www.thetvdb.com/banners/graphical/5b5a9e3a86e02.jpg
poster2: https://www.thetvdb.com/banners/_cache/posters/5b5a2a04eda7c.jpg
fanart2: https://www.thetvdb.com/banners/_cache/fanart/original/161511-34.jpg
extrainfo2: ★ 9.0 - Showtime
title2: Shameless (US)
subtitle2: Face It, You're Gorgeous
airdate2: 2018-10-15T01:00:00Z
hasFile2: false
info2: S09E06
friendly_name: Sonarr_Upcoming media
```

Could this be due to the shows releasing at the same time?
The Card looks like this:
```
      - type: custom:upcoming-media-card
        service: sonarr
        image_style: poster
        date: ddmm
        clock: 24
        max: 7
```

**Comment by maykar** [comment]
Interesting. Which show is the one displaying?

**Comment by FallenLeave91** [comment]
In this case Family Guy. Last Week it was Shameless. But i don´t know if it was the first or second entry.

**Comment by maykar** [comment]
I was unable to replicate this issue myself, but I have also completely changed how the items are retrieved and am pretty confident this should have solved it. Will reopen if this is not the case.

**Comment by maykar** [comment]
This was still an issue, but has just been fixed. Big thanks to thomasloven for finding and providing fix.
