### ISSUE TITLE
Don't see Upcoming Media Card in HA

### ISSUE THREAD

**Issue by PrzemekSkw** [custom-cards/upcoming-media-card#73]
Hello, I try to install Upcoming Media Card on my HA server (Dietpi -Debian Bullseye on MiniPC). Firrst anfter start I add integration to Sonarr. Next I wat to add other integrations (Radarr, Emby, Trakt) do I install HACS. In HACS I add repository in User interface > `Upcoming Media Card`. In HACS in Integrations I add `Radarr Upcoming Media` `Sonarr Upcoming Media`, `Trakt` and `Emby Latest Media`. I go to installation guide and do like this:

> Install this card by copying upcoming-media-card.js to your www/custom-lovelace/ folder. If you're copy/pasting the code always copy from raw files on github (button on top right when viewing code).
> Include it in its own folder like so: www/custom-lovelace/upcoming-media-card/upcoming-media-card.js
> 
I copy `upcoming-media-card.js` file from `/homeassistant/www/community/upcoming-media-card/` to `/homeassistant/www/custom-lovelace/upcoming-media-card/`

I don't understand the rest of that guide:

> This goes into ui-lovelace.yaml under "resources:"
> 
> resources:
> - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
>   type: js
> This goes into one of your views under "cards:" in the same file
> 
>   - type: custom:upcoming-media-card
>     entity: sensor.sonarr_upcoming_media
> 

Can somebody explain me where are `resources` and what to do in next steps?

Regards,
Przemek

**Comment by yfands** [comment]
Same here, installed via HACS, but a no show in cards.

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4985
Installed Version | 1.16.0
Stage | running
Available Repositories | 898
Installed Repositories | 97

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 116.7 GB
disk_used | 16.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 68
views | 36
mode | storage

</details>

**Comment by dirtymurt** [comment]
OK, it's just a case of reading the documentation properly. You have to use one of the official customcomponents to feed it. I can't get the Sonarr one to work because I'm using a seedbox and the fact that I need to add a port scuppers it for me. However, recently added to plex works like a charm

`type: custom:upcoming-media-card
title: New Shows
entity: sensor.plex_recently_added_show
image_style: fanart
title_size: small
line1_size: small
line2_size: small
line3_size: small
line4_size: small
flag: false`

that's the code to make it appear in your lovelace dash, after you have created the https://github.com/custom-components/sensor.plex_recently_added component

**Comment by PrzemekSkw** [comment]
Hi, @dirtymurt I do exactly what You say:
1. Install Plex Recently Added from HACS
2. Install Upcoming Media Card from HACS
3. Add to configuration.yaml:
```
sensor:
  - platform: plex_recently_added
    name: Recently Added Movies # will create sensor.recently_added_movies
    token: xxxxxxxxxxxxxxxxxxxxx
    host: 192.168.0.19
    port: 32400
    section_types:
      - movie
  - platform: plex_recently_added
    name: Recently Added TV  # will create sensor.recently_added_tv
    token: xxxxxxxxxxxxxxxxxxxxxxx
    host: 192.168.0.19
    port: 32400
    section_types:
      - show
      ```
4. Add new lovelace card:
      ```
      type: custom:upcoming-media-card
title: New Shows
entity: sensor.plex_recently_added_show
image_style: fanart
title_size: small
line1_size: small
line2_size: small
line3_size: small
line4_size: small
flag: false
```
5. Restart HA, clear browser cache.
There's no entity about Plex Recently Added in my HA.
In lovelace I see only white small card with text `New Shows`.

Regards.

**Comment by dirtymurt** [comment]
I can;t see anything wrong with that. are you sure your plex token is correct? Maybe restart PLEX?

**Comment by PrzemekSkw** [comment]
Finally I can make it work with Sonarr and Radarr cards. 
Thanks.
