### ISSUE TITLE
TypeError hass is undefined with vertical-stack-in-card

### ISSUE THREAD

**Issue by Psychoses** [custom-cards/upcoming-media-card#75]
## Describe the bug:
blank page when use Upcoming-Media-Card with https://github.com/ofekashery/vertical-stack-in-card

## Error:
```
Uncaught (in promise) TypeError: hass is undefined
    set hass upcoming-media-card.js:13
    createCardElement vertical-stack-in-card.js:100
    promises vertical-stack-in-card.js:25
    renderCard vertical-stack-in-card.js:25
    setConfig vertical-stack-in-card.js:17
```

## Troubleshooting Guide:
inspired by
https://github.com/denysdovhan/vacuum-card/commit/59fcadd37df1bf8fd95a7ad243f56191478592a0
https://github.com/denysdovhan/vacuum-card/issues/133

This change around the line 13 seems do the trick
```
...
    const entity = this.config.entity;
    if (!hass) {
      return null;
    }
    if (!hass.states[entity]) return;
...
```

**Comment by mkanet** [comment]
A lot has changed since this issue was opened.  Please try again using the latest versions of UMC and vertical-stack-in-card.  If you still can't find a solution or workaround, please open a new ticket.
