### ISSUE TITLE
Card size is fixed

### ISSUE THREAD

**Issue by thomasloven** [custom-cards/upcoming-media-card#8]
getCardSize returns a fixed value of 3, regardless of the contents of the card.
It might make sense to have getCardSize return the expected average or max size of the card instead, for better automatic layouting.

https://developers.home-assistant.io/docs/en/lovelace_custom_card.html#api:
> Your card can define a getCardSize method that returns the size of your card as a number. A height of 1 is equivalent to 50 pixels. This will help Home Assistant distribute the cards evenly over the columns.

**Comment by maykar** [comment]
Added a true getCardSize. The card uses responsive CSS to size according to available space and unfortunately getCardSize is called before the sizing takes place. The solution was to use an average size, so it's not perfect, but far better than the fixed size option.
