### ISSUE TITLE
Card is not showing up in UI nor recognised when adding it as a custom card in ui.

### ISSUE THREAD

**Issue by ToXinE** [custom-cards/upcoming-media-card#80]
## Describe the bug:

I'm not able to use the "Upcoming Media Card" it's not detected by HA despite I've installed it with HACS.

## Config YAML:
```
- type: custom:upcoming-media-card
  entity: sensor.radarr_upcoming_media
  title: Upcoming Movies
```

## Components:
I tried with sonarr or radarr and it's the same with both.

## HA Error:
(not useful as no errors where detected)

## Troubleshooting Guide:

The troobleshooting page needs to be refreshed as paths are not the same when installing with the HACS addon.

## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | running
Available Repositories | 931
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 29.0 GB
disk_used | 6.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Network UPS Tools (0.9.0), Mosquitto broker (6.0.1), Studio Code Server (4.0.0), SSH & Web Terminal (10.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 2
views | 6
mode | storage

</details>

## Screenshots:
![image](https://user-images.githubusercontent.com/6205053/149291409-e5d1d8fa-50f1-4370-aff7-75ce474849c7.png)
![image](https://user-images.githubusercontent.com/6205053/149292030-9b9649dd-59e5-4462-9ef1-62ac69b0f1e1.png)
![image](https://user-images.githubusercontent.com/6205053/149292726-1a5d0233-0104-4785-b212-edb397223626.png)
ressources added by the HACS installation.

**Comment by DavidFW1960** [comment]
Have you added the custom-components as well? Does the sensor.radarr_upcoming_media exist (or Sonarr)

**Comment by ToXinE** [comment]
The sensors does exists as you can see here: ![image](https://user-images.githubusercontent.com/6205053/149292030-9b9649dd-59e5-4462-9ef1-62ac69b0f1e1.png).
Is this what you meant with "custom-components" ?

**Comment by ToXinE** [comment]
here is what I pasted in my configuration.yaml: 
`sensor:
  - platform: sonarr_upcoming_media
    api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    host: 192.168.0.1
    port: 8989
    days: 7
    ssl: false
    max: 10
  - platform: radarr_upcoming_media
    api_key: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    host: 192.168.0.1
    port: 7878
    days: 14
    ssl: false
    theaters: false
    max: 10`

**Comment by ToXinE** [comment]
the custom-components seems to work: When I set Attribut to 'Data', It display something. It only seems to be displayed in a nice way thought the custom card upcoming media.
![image](https://user-images.githubusercontent.com/6205053/149587856-35c6cc07-7400-4b2d-8e63-d5dbae7b2090.png)

**Comment by DavidFW1960** [comment]
You need to add it to Lovelace like this. You can do it in the GUI as well.
![image](https://user-images.githubusercontent.com/36390762/149644923-e0a1d719-c0ee-4bd4-aa4a-c2a5d0875eee.png)

**Comment by ToXinE** [comment]
ok, it's working now : 
the help page said: 
```
- type: custom:upcoming-media-card
entity: sensor.radarr_upcoming_media
title: Upcoming Movies
```
I just had to remove the "-" in front of "- type:" ...

Thank you for your help !

**Comment by DavidFW1960** [comment]
> I just had to remove the "-" in front of "- type:" ...

yeah if you are in the RAW yaml config you need the '-' but in the GUI you don't
