### ISSUE TITLE
Display time problem

### ISSUE THREAD

**Issue by Gilumac** [custom-cards/upcoming-media-card#81]
## Describe the bug:
Output data has correct datetime in aired field. Card adds +1 hour when display time.

`data: >-
  [{"title_default": "$title", "line1_default": "$studio", "line2_default":
  "$release", "line3_default": "$number - $rating - $runtime", "line4_default":
  "$genres", "icon": "mdi:eye-off"}, {"airdate": "2022-01-30T17:45:53Z",
  "poster": "https://media.teleman.pl/photos/720x445/Ostatni-Smok-1996.jpg",
  "title": "Ostatni smok", "studio": "TVN 7", "release": "$day $time"},
  {"airdate": "2022-01-30T17:55:51Z", "poster":
  "https://media.teleman.pl/photos/720x445/Dziewczyna-z-Jersey.jpeg", "title":
  "Dziewczyna z Jersey", "studio": "TV Puls", "release": "$day $time"},
  {"airdate": "2022-01-30T18:10:52Z", "poster":
  "https://media.teleman.pl/photos/720x445/Wciaz-Ja-Kocham-2010.jpg", "title":
  "Wci\u0105\u017c j\u0105 kocham", "studio": "ale kino+", "release": "$day
  $time"}, {"airdate": "2022-01-30T20:00:50Z", "poster":
  "https://media.teleman.pl/photos/720x445/Cudzoziemiec2017.jpeg", "title":
  "Cudzoziemiec", "studio": "TV Puls", "release": "$day $time"}, {"airdate":
  "2022-01-30T20:00:50Z", "poster":
  "https://media.teleman.pl/photos/720x445/Monstrum_jcTfjRw.jpeg", "title":
  "Monstrum", "studio": "TVP Kultura", "release": "$day $time"}, {"airdate":
  "2022-01-30T20:00:51Z", "poster":
  "https://media.teleman.pl/photos/720x445/Wyspa_1.jpeg", "title": "Wyspa",
  "studio": "TVN 7", "release": "$day $time"}, {"airdate":
  "2022-01-30T20:00:51Z", "poster":
  "https://media.teleman.pl/photos/720x445/Wyscig-z-Czasem_1.jpeg", "title":
  "Wy\u015bcig z czasem", "studio": "Stopklatka", "release": "$day $time"},
  {"airdate": "2022-01-30T20:00:52Z", "poster":
  "https://media.teleman.pl/photos/720x445/Milosc-w-Nowym-Jorku-2000.jpg",
  "title": "Mi\u0142o\u015b\u0107 w Nowym Jorku", "studio": "Tele 5", "release":
  "$day $time"}, {"airdate": "2022-01-30T20:05:51Z", "poster":
  "https://media.teleman.pl/photos/720x445/Wstrzasy.jpeg", "title":
  "Wstrz\u0105sy", "studio": "TV 4", "release": "$day $time"}, {"airdate":
  "2022-01-30T20:10:50Z", "poster":
  "https://media.teleman.pl/photos/720x445/Male-Rzeczy2021.jpeg", "title":
  "Ma\u0142e rzeczy", "studio": "HBO", "release": "$day $time"}, {"airdate":
  "2022-01-30T20:15:50Z", "poster":
  "https://media.teleman.pl/photos/720x445/Niezapomniany2017.jpeg", "title":
  "Niezapomniany", "studio": "TVN", "release": "$day $time"}, {"airdate":
  "2022-01-30T21:00:51Z", "poster":
  "https://media.teleman.pl/photos/720x445/Kryzys2021.jpeg", "title": "Kryzys",
  "studio": "CANAL+ Premium", "release": "$day $time"}, {"airdate":
  "2022-01-30T21:00:52Z", "poster":
  "https://media.teleman.pl/photos/720x445/Tanczacy-Pies2018.jpeg", "title":
  "Ta\u0144cz\u0105cy pies", "studio": "CBS Europa", "release": "$day $time"},
  {"airdate": "2022-01-30T21:15:53Z", "poster":
  "https://media.teleman.pl/photos/720x445/Ostatnia-Rodzina-2016.jpg", "title":
  "Ostatnia rodzina", "studio": "TVP Polonia", "release": "$day $time"},
  {"airdate": "2022-01-30T22:10:53Z", "poster":
  "https://media.teleman.pl/photos/720x445/Wojenny-Biznes-2008.jpg", "title":
  "Wojenny biznes", "studio": "TV Puls", "release": "$day $time"}, {"airdate":
  "2022-01-30T22:55:52Z", "poster":
  "https://media.teleman.pl/photos/720x445/Zagubiony-Czas-2011.jpg", "title":
  "Zagubiony czas", "studio": "TVP 2", "release": "$day $time"}]
friendly_name: teleman
`
Display:
[Image](https://ibb.co/fptWf3f)

## Config YAML:
`- title: Dziś w tv
    path: dzis-w-tv
    icon: mdi:television-classic
    badges: []
    cards:
      - type: custom:upcoming-media-card
        entity: sensor.teleman
        title: Dziś w tv
        max: 15
        image_style: fanart
        clock: 24`

## Components:
My new custom component. It scrape site and display what's today movies TV
[https://github.com/Gilumac/teleman](https://github.com/Gilumac/teleman)

## HA Error:
There is no error

## Home Assistant Version:
Home Assistant 2021.12.7

## Screenshots:
attached

## Additional Context:
none

**Comment by mkanet** [comment]
There hasn't been any activity for this issue in years.  Please try the latest UMC to see if the issue still exists or not.  If so, please open a new issue; include all the information needed to recreate the issue.
