### ISSUE TITLE
UMC prevents an entire view to display in 2022.4

### ISSUE THREAD

**Issue by Stooovie** [custom-cards/upcoming-media-card#82]
## Describe the bug:
In HA 2022.4, UMC prevents the entire view to load.
## Config YAML:
`      - type: custom:upcoming-media-card
        entity: sensor.kodi_recently_added_tv
        title: Recently Added Episodes
        image_style: fanart
        date: ddmm
        clock: 24
      - type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
        title: Upcoming TV
        image_style: fanart
      - type: custom:upcoming-media-card
        entity: sensor.kodi_recently_added_movies
        title: Recently Added Movies
        image_style: fanart`

## HA Error:
No error in HA log. Edge Dev Console shows this:
` Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at UpcomingMediaCard.set hass [as hass] (upcoming-media-card.js?hacstag=146783593043:16:88)
    at i.value (hui-masonry-view.ts:44:1)
    at hui-masonry-view.ts:44:1
    at Array.map (<anonymous>)
    at i.value (hui-masonry-view.ts:44:1)
    at i.value (hui-masonry-view.ts:44:1)
    at i.value (hui-masonry-view.ts:44:1)
    at i.performUpdate (styles.ts:368:1)
    at i.scheduleUpdate (styles.ts:368:1)
set hass @ upcoming-media-card.js?hacstag=146783593043:16
value @ hui-masonry-view.ts:44
(anonymous) @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
value @ hui-masonry-view.ts:44
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
o @ styles.ts:368
b @ styles.ts:368
i @ hui-masonry-view.ts:44
E @ typography.js:181
t @ typography.js:181
value @ hui-root.ts:516
(anonymous) @ hui-root.ts:516
setTimeout (async)
(anonymous) @ 8e21afb3.js:1
requestAnimationFrame (async)
i @ 8e21afb3.js:1
value @ hui-root.ts:516
_$AE @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
t @ home-assistant.ts:32
(anonymous) @ home-assistant.ts:32
i @ typography.js:181
s @ typography.js:181
value @ hui-root.ts:516
value @ hui-root.ts:516
handleEvent @ styles.ts:368
fire @ typography.js:181
_itemActivate @ 616db214.js:2
_activateHandler @ 616db214.js:2
_activateHandler @ 616db214.js:2
_activateHandler @ paper-tabs.js:229
(anonymous) @ typography.js:181
M @ typography.js:181
U @ typography.js:181
click @ typography.js:181
R @ typography.js:181
`

## Home Assistant Version:
2022.4

## Screenshots:

![Screenshot 2022-04-06 213205](https://user-images.githubusercontent.com/10572373/162054456-d0ea1079-bbc1-4d23-bb71-bcf3ee069f92.png)

**Comment by jncanches** [comment]
+1 on this

**Comment by armdan** [comment]
Yeah, after the upgrade it broke my setup as well

**Comment by Arnaud-Albrecht** [comment]
Same, anyone found a solution?

**Comment by boralyl** [comment]
What's the `data` attribute of your sensor in the devloper tools on the states tab?

**Comment by Arnaud-Albrecht** [comment]
State : Online

**Comment by boralyl** [comment]
It would be under the `Attributes` column (you should see a big json blob):
![image](https://user-images.githubusercontent.com/109865/166181620-4b2398e5-713e-40ab-b5c6-bf48c3fa7706.png)

**Comment by Arnaud-Albrecht** [comment]
<img width="934" alt="Capture d’écran 2022-05-02 à 13 44 35" src="https://user-images.githubusercontent.com/9463727/166181729-e6f40671-1e56-48a8-96d9-c8eca3d79354.png">

**Comment by Arnaud-Albrecht** [comment]
So the bug actually come from the plex component?

**Comment by boralyl** [comment]
@Arnaud-Albrecht Based on what data is shown there, it does seem like the issue might be with the plex component.  You can see the only attribute you have is `friendly_name`, if there is no `data` attribute this card can't display anything.

**Comment by Arnaud-Albrecht** [comment]
Yep, i'll investigate a bit more. Cheers

**Comment by Arnaud-Albrecht** [comment]
Ok, so it seems that the update of april for some reason removed the plex recently added component(that you add from HACS).

It did not remove the config in the yaml. So just had to add the integration and restart Home Assistant.

Thanks for pointing me in the right direction

**Comment by mkanet** [comment]
FYI, UMC and a few of the other original integration including [plex recently added](https://github.com/custom-components/sensor.plex_recently_added) is supported again and will be added back to HACS in the relative near future.  In the meantime, you can add the repos manually to HACS (if you already removed them from your Home Assistant instance).  You can also open an issue if you're having a problem with the Plex Recently Added integration.
