### ISSUE TITLE
Sonarr cannot be reached.

### ISSUE THREAD

**Issue by TheLion** [custom-cards/upcoming-media-card#85]
## Describe the bug:
The card for Radarr works fine, but Sonarr reports "192.168.206.210 cannot be reached" in the state is developer tools. 

## Config YAML:

- platform: radarr_upcoming_media
  api_key: xx
  host: 192.168.206.210
  port: 30025
  days: 14
  ssl: false
  theaters: false
  max: 10
- platform: sonarr_upcoming_media
  api_key: xxx
  host: 192.168.206.210
  port: 30027
  days: 14
  ssl: false
  max: 10

## Components:
Issue only is with Sonarr, Radarr works just fine

## HA Error:
Nothing particular in the log for the Sonarr card. 

## Troubleshooting Guide:
The Sonarr webinterface works just fine on the used IP-address and port. Other application read the information from Sonarr without issues. 

## Home Assistant Version:
Currently v2024.2.1, but it happens from the beginning, with earlier 2023.x version. Has never worked correctly. 

## Screenshots:
Shows Radarr en Plex working fine, Sonarr not. 
![IMG_0569](https://github.com/custom-cards/upcoming-media-card/assets/3755011/aba23665-0205-47b5-bb97-acbcb671db02)

## Additional Context:
Don't have anything to add. If you got questions, please ask.

**Comment by TheLion** [comment]
There seems to be an active thread on the HA forum about this. 
https://community.home-assistant.io/t/sonarr-v3-failed-to-connect/264401

**Comment by mkanet** [comment]
Hi @TheLion are you using Sonarr V4?  If so, you need to install the latest official [Sonarr Upcoming Media integration](https://github.com/custom-components/sensor.sonarr_upcoming_media) to support Sonarr V4.

BTW:  I am in the process of adding all the official "Upcoming Media" repos back to HACS with lots of brand-new goodies.  Stay tuned.  I'll announce it on the main Upcoming Media Card forum thread.

**Comment by TheLion** [comment]
> Hi @TheLion are you using Sonarr V4? If so, you need to install the latest official [Sonarr Upcoming Media integration](https://github.com/custom-components/sensor.sonarr_upcoming_media) to support Sonarr V4.

Yes, using v4. Great. Will do that. 

> BTW: I am in the process of adding all the official "Upcoming Media" repos back to HACS with lots of brand-new goodies. Stay tuned. I'll announce it on the main Upcoming Media Card forum thread.

Can't wait ;-)

**Comment by pmele** [comment]
Using Sonarr V3.0.10.1567 and the card cannot locate the server. All parameters are correct.  Radarr on the same server works fine, Sonarr is just using a different port.  I tried using the IP Address and the domain name, nothing

**Comment by mkanet** [comment]
@pmele my appologies, Sonarr V3 is not in production anymore.  The current version is Sonarr V4.  It only takes a minutes to upgrade.  After you upgrade, it should work just fine.

https://sonarr.tv/#download

**Comment by pmele** [comment]
Yep, that was the issue.  thank you!
