### ISSUE TITLE
image.includes is not a function

### ISSUE THREAD

**Issue by FuzzyMistborn** [custom-cards/upcoming-media-card#87]
## Describe the bug:

Card does not display for Radarr, it does for Sonarr

## Config YAML:

```
type: custom:upcoming-media-card
entity: sensor.radarr_upcoming_media
```

## Components:

Sonarr and Radarr upcoming media cards

## HA Error:

None

## Home Assistant Version:

2024.02.6

## Screenshots:

![image](https://github.com/custom-cards/upcoming-media-card/assets/16689090/6d9df464-6d8d-4c5c-abcd-6cd1573fbb83)

## Additional Context:

I'm stumped.  This was working before I updated, but I've tried rolling back to older versions without luck.  I also don't get why it's working for Sonarr but not Radarr.

**Comment by FuzzyMistborn** [comment]
And rebooted again (for like the 4th time) to fix something else and....it's working.  Go figure.

**Comment by mkanet** [comment]
@FuzzyMistborn thank you so much for reporting that issue!  I just pushed a fix to prevent that issue from happening.  As you know, I've added several new features very recently.  Please let me know if you run into any other issues.  Im still in the process of updating the documentation for all the new features.
