### ISSUE TITLE
$aired should include the year

### ISSUE THREAD

**Issue by mcattle** [custom-cards/upcoming-media-card#89]
Presently, the `$aired` display date includes the aired month and day, but it doesn't include the year (such as for movies).

As an example, "10 Things I Hate About You" shows an `$aired` date of `03/31`, leaving out the year of `1999`.

I'd like to see `$aired` include the aired year and also be formattable, such as the readable `March 31, 1999`, or the ISO `1999-03-31`.

**Comment by mkanet** [comment]
I think that's a good idea.  I'll look into this.  Thanks for the idea!

**Comment by mkanet** [comment]
Done.  I just updated the repo. 

![Screenshot 03-30-2024 at 03 24 24 PM](https://github.com/custom-cards/upcoming-media-card/assets/811008/7ded3fca-59f4-4e86-879b-a4771e9243f3)

**Comment by mkanet** [comment]
Thanks for letting me know.  I just fixed it.  It should show as 0.5.1 now

**Comment by mkanet** [comment]
Hey @mcattle not sure if you're still following this closed issue.  I just wanted you to know that , I _just_ added more flexibility to custom date formats. You can now specify date formats such as: date: yyddmm, date: ddmm, date: mmyy, etc; which will also affect $Release date format as well.  That way you have better control of how you want the date displayed.

**Comment by mcattle** [comment]
That's great, thanks!

**Comment by infectionform** [comment]
Hi mcattle, sorry to jump on this old issue but I just wanted to ask if it's possible to add a 4 digit year as a valid output when pulling from the $aired attribute?
At the moment, using 'date: yyyy' just returns "26/26" for a movie that came out in 2026, obviously the desired output would just be "2026".
I might be the only one, but I really like to see the full 4 digit year (usually in parenthesis) when I see a movie title in my collection.

**Comment by mkanet** [comment]
@infectionform, thanks for the great suggestion. I just implemented this, and while I was at it, added some more flexibility and fixed a couple of bugs related to the **date:** setting.  Now you can do stuff like below.  Notice, I even supported your request for **(2026)** with surrounding parentheses.

You should see the update on HACS for Version 0.6.4 soon.  It will have this new enhancement.

More flexible **date:** formats:

| **Format**         | **Output**     |
|--------------------|----------------|
| date: yyyy         | **2026**       |
| date: (yyyy)       | **(2026)**     |
| date: m/d/yyyy     | **5/8/2026**   |
| date: m/dd/yy      | **5/08/26**    |

Also supports mixed combos like mm/d/yy, m/dd/yyyy, etc.
