### ISSUE TITLE
Date is listed as being undefined in the cards.

### ISSUE THREAD

**Issue by davislp** [custom-cards/upcoming-media-card#95]
## Describe the bug:
When using the string $date, the card displays "undefined" instead of the date. I have defined 'date: mmdd' in the card's config, but that has no effect.

## Config YAML:

```
type: custom:upcoming-media-card
entity: sensor.trakt_upcoming_movies
title: Upcoming Movies
enable_transparency: true
date: mmdd
image_style: fanart
hide_empty: true
title_text: $title
line1_text: $date
line2_text: $empty
line3_text: $empty
line4_text: $empty
max: 10
```

## Components:
Using Trakt, the issue happens with upcoming movies, shows, season primers, etc.

## HA Error:
None.

## Troubleshooting Guide:

I did review the troubleshooting guide, but it did not solve my issue.

## Home Assistant Version:
Core 2024.6.3
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240610.1

## Screenshots:
![screenshot](https://github.com/custom-cards/upcoming-media-card/assets/42299530/4f764318-da63-48b9-99cb-3c1b7842deb1)

**Comment by mkanet** [comment]
@davislp  please edit the YAML code you posted, its not displayed correctly here.

**Comment by davislp** [comment]
> @davislp please edit the YAML code you posted, its not displayed correctly here.

Updated.

**Comment by mkanet** [comment]
Thanks for posting.  Does your `sensor.trakt_upcoming_movies` sensor actually have any movies to display?   _Go to settings/Developer Tools/STATES in Home Assistant; and type the name of your sensor name to verify._ 

Currently, my trakt sensor `sensor.trakt_upcoming_movies`  doesn't have any data to display either (see below screenshot); hence, UMC card also doesnt display any movies similar to your screenshot.

**Currently, as you can see my `sensor.trakt_upcoming_movies` sensor doesn't have any data:**  
![image](https://github.com/custom-cards/upcoming-media-card/assets/811008/f24c046e-7104-462a-905a-1b61d37612be)

If there is actual data in the sensor like:
![image](https://github.com/custom-cards/upcoming-media-card/assets/811008/d277b4cb-b105-4103-b4e9-fc57ed4bfc03)

..and use a very simple YAML code like below:
```
type: custom:upcoming-media-card
entity: sensor.trakt_upcoming_dvd
title: New Bluray & DVD
image_style: poster
hide_empty: true
```
It would look like:
![image](https://github.com/custom-cards/upcoming-media-card/assets/811008/54dfbb12-2d5e-4e86-a60c-a0259c4b199d)

A good starting point would be to find a sensor with data, then setup a very basic card (like the below YAML code).  Once you see some items populate in the respective attribute data (movies or shows depending on the sensor), you can then customize each line, if you wish.

```
type: custom:upcoming-media-card
entity: sensor.trakt_upcoming_dvd
title: New Bluray & DVD
image_style: poster
hide_empty: true
```

**Comment by davislp** [comment]
My Trakt sensor does have data:

![screenshot 2](https://github.com/custom-cards/upcoming-media-card/assets/42299530/783efabc-1565-490d-84ae-452984bdcf53)

And when I create a simple card, it does display a date. The issue only arises when using the `$date` string. It's a minor thing, but movies don't actually release at the times listed, so I would prefer to omit the time from the card.

![screenshot 3](https://github.com/custom-cards/upcoming-media-card/assets/42299530/2dd201c2-401d-4678-bcb6-70c31bf897fa)

**Comment by mkanet** [comment]
Thank you so much for bringing this to my attention.  $date and a few other keywords were completely broken in the code.  I just fixed it so the keywords work as intended; including `$empty`.  I'll push out a new version in the next day or so with these fixes and a couple of others.  Ill close this issue once you confirm it all works correctly.

**Comment by davislp** [comment]
Thanks for being so awesome.

**Comment by mkanet** [comment]
@davislp Upgrade UMC to Version `0.5.7`.  While fixing this, I also added more flexibility to custom date formats.  You can now specify date formats such as:  `date: yyddmm`, `date: ddmm`, `date: mmyy`, etc; which will also affect `$Release` date format as well.

The below YAML code will work as intended.  Just note that `date: mmdd`  will display only month and day I.E., `06/19`.  If you want year as well, you would use `date: mmddyy` , I.E., `06/19/24`.
```
type: custom:upcoming-media-card
entity: sensor.trakt_upcoming_movies
title: Upcoming Movies
enable_transparency: true
date: mmdd
image_style: fanart
hide_empty: true
title_text: $title
line1_text: $date
line2_text: $empty
line3_text: $empty
line4_text: $empty
max: 10
``

**Comment by davislp** [comment]
Works perfectly. Thank you again for the quick response.
