### ISSUE TITLE
upcoming-media-card remains on the archived list that was created >2 years ago, produces instructions that it should be deleted.  When is this going to be resolved?

### ISSUE THREAD

**Issue by douginoz** [custom-cards/upcoming-media-card#98]
## Describe the bug:
HACS displays warning that this card should be deleted because it is on the Archived list https://github.com/hacs/default/pull/1373/files
There's still new releases coming out for this card but this issues still hasn't been resolved
## Additional Context:
The warning encourages users to select "Delete" in order to have the message removed but that removes the custom card completely. 

It could be ignored, but it's been years and still appears and hasn't been addressed. Is this just a housekeeping issue or something that can be easily resolved with some communication?

**Comment by mkanet** [comment]
Very soon.  I already submitted the PR over 4 months ago.  Typically, it takes around 4 months HACS moderators to approve PRs.  So, it should be coming up soon.
